#!/bin/bash
# Script untuk generate Vercel deployment checklist

echo "🚀 Suka Bakar Dimsum - Vercel Deployment Checklist"
echo "=================================================="
echo ""
echo "STEP 1: Persiapan GitHub"
echo "  ✅ Repository sudah push ke GitHub"
echo "  ✅ URL: https://github.com/sukabakardimsum/sukabakardimsum_dasboard"
echo ""
echo "STEP 2: Setup Vercel Account"
echo "  📍 Buka: https://vercel.com"
echo "  🔐 Login dengan GitHub (sukabakardimsum)"
echo "  ✅ Authorize Vercel"
echo ""
echo "STEP 3: Create Project"
echo "  1. Klik 'New Project'"
echo "  2. Pilih repository: sukabakardimsum_dasboard"
echo "  3. Klik 'Import'"
echo ""
echo "STEP 4: Configure Project"
echo "  Framework: Vite"
echo "  Root Directory: ./"
echo "  Build Command: npm run build"
echo "  Output Directory: dist"
echo ""
echo "STEP 5: Add Environment Variables"
echo "  Variable 1:"
echo "    NAME: VITE_SUPABASE_URL"
echo "    VALUE: https://uapefmshmofglbidikbc.supabase.co"
echo ""
echo "  Variable 2:"
echo "    NAME: VITE_SUPABASE_ANON_KEY"
echo "    VALUE: sb_publishable_btlBprDJg2MfS8p4ivVCkg_FvDi7fHj"
echo ""
echo "STEP 6: Deploy"
echo "  Klik tombol 'Deploy'"
echo "  Tunggu sampai selesai (2-5 menit)"
echo ""
echo "STEP 7: Verify"
echo "  Buka URL Vercel yang diberikan"
echo "  Login test: owner / yanu"
echo "  Cek apakah database terhubung"
echo ""
echo "=================================================="
echo "✅ Setup Selesai!"
echo ""
